//
//  SSJobsLookups.m
//  SixStreams
//
//  Created by Anping Wang on 6/13/14.
//  Copyright (c) 2014 SixStream. All rights reserved.
//

#import "SSJobsLookups.h"
#import "SixStreams.h"

@implementation SSJobsLookups



- (id) getLovs
{
    NSMutableDictionary * lovs = [NSMutableDictionary dictionary];
        
    NSDictionary *metroAreas =
    @{
      @"1":@{@"latitude":@"35.47561725",@"longitude":@"-97.5247127",@"name":@"Oklahoma City, OK"},
      @"2":@{@"latitude":@"45.51316694",@"longitude":@"-122.6585075",@"name":@"Portland, OR"},
      @"3":@{@"latitude":@"30.29087698",@"longitude":@"-81.62454564",@"name":@"Jacksonville, FL"},
      @"4":@{@"latitude":@"38.21502414",@"longitude":@"-85.69160417",@"name":@"Louisville, KY"},
      @"5":@{@"latitude":@"27.98475983",@"longitude":@"-82.47642098",@"name":@"Tampa, FL"},
      @"6":@{@"latitude":@"35.8106018",@"longitude":@"-78.64748411",@"name":@"Raleigh, NC"},
      @"7":@{@"latitude":@"34.13133584",@"longitude":@"-117.2979061",@"name":@"San Bernardino, CA"},
      @"8":@{@"latitude":@"37.55005406",@"longitude":@"-77.47124633",@"name":@"Richmond, VA"},
      @"9":@{@"latitude":@"29.76783986",@"longitude":@"-95.40790893",@"name":@"Houston, TX"},
      @"10":@{@"latitude":@"36.86373",@"longitude":@"-76.012395",@"name":@"Virginia Beach, VA"},
      @"11":@{@"latitude":@"32.80826972",@"longitude":@"-96.80927303",@"name":@"Dallas, TX"},
      @"12":@{@"latitude":@"40.72879529",@"longitude":@"-111.8970241",@"name":@"Salt Lake City, UT"},
      @"13":@{@"latitude":@"29.47301473",@"longitude":@"-98.50781504",@"name":@"San Antonio, TX"},
      @"14":@{@"latitude":@"41.588394",@"longitude":@"-93.619191",@"name":@"Des Moines, IA"},
      @"15":@{@"latitude":@"41.76099549",@"longitude":@"-72.68912404",@"name":@"Hartford, CT"},
      @"16":@{@"latitude":@"39.73843274",@"longitude":@"-104.9811504",@"name":@"Denver, CO"},
      @"17":@{@"latitude":@"39.98840212",@"longitude":@"-75.14948373",@"name":@"Philadelphia, PA"},
      @"18":@{@"latitude":@"43.046435",@"longitude":@"-87.95053098",@"name":@"Milwaukee, WI"},
      @"19":@{@"latitude":@"38.89866484",@"longitude":@"-77.02719284",@"name":@"Washington, DC"},
      @"20":@{@"latitude":@"35.21271862",@"longitude":@"-80.83673404",@"name":@"Charlotte, NC"},
      @"21":@{@"latitude":@"37.76891744",@"longitude":@"-122.4230505",@"name":@"San Francisco, CA"},
      @"22":@{@"latitude":@"36.15270909",@"longitude":@"-115.1872541",@"name":@"Las Vegas, NV"},
      @"23":@{@"latitude":@"42.36202332",@"longitude":@"-83.08482407",@"name":@"Detroit, MI"},
      @"24":@{@"latitude":@"40.74811991",@"longitude":@"-73.98639735",@"name":@"New York, NY"},
      @"25":@{@"latitude":@"51.03944",@"longitude":@"-114.07967",@"name":@"Calgary, AB"},
      @"26":@{@"latitude":@"37.371201",@"longitude":@"-121.969586",@"name":@"Silicon Valley"},
      @"27":@{@"latitude":@"33.49769055",@"longitude":@"-86.80229941",@"name":@"Birmingham, AL"},
      @"28":@{@"latitude":@"42.90879377",@"longitude":@"-78.8311545",@"name":@"Buffalo, NY"},
      @"29":@{@"latitude":@"44.98206916",@"longitude":@"-93.29692304",@"name":@"Minneapolis, MN"},
      @"30":@{@"latitude":@"38.631974",@"longitude":@"-90.191176",@"name":@"St Louis, MO"},
      @"31":@{@"latitude":@"49.252502",@"longitude":@"-123.10708",@"name":@"Vancouver, BC"},
      @"32":@{@"latitude":@"43.670197",@"longitude":@"-79.3927",@"name":@"Toronto, ON"},
      @"33":@{@"latitude":@"30.29949025",@"longitude":@"-97.75492156",@"name":@"Austin, TX"},
      @"34":@{@"latitude":@"33.51268581",@"longitude":@"-112.0745736",@"name":@"Phoenix, AZ"},
      @"35":@{@"latitude":@"45.53754",@"longitude":@"-73.593765",@"name":@"Montreal, QC"},
      @"36":@{@"latitude":@"40.44523137",@"longitude":@"-79.99395529",@"name":@"Pittsburgh, PA"},
      @"37":@{@"latitude":@"29.96451775",@"longitude":@"-90.06445051",@"name":@"New Orleans, LA"},
      @"38":@{@"latitude":@"41.8227865",@"longitude":@"-71.42355786",@"name":@"Providence, RI"},
      @"39":@{@"latitude":@"43.15616134",@"longitude":@"-77.61736243",@"name":@"Rochester, NY"},
      @"40":@{@"latitude":@"36.15052449",@"longitude":@"-86.77628418",@"name":@"Nashville, TN"},
      @"41":@{@"latitude":@"39.99235653",@"longitude":@"-82.98797049",@"name":@"Columbus, OH"},
      @"42":@{@"latitude":@"41.86604874",@"longitude":@"-87.67099447",@"name":@"Chicago, IL"},
      @"43":@{@"latitude":@"25.78723665",@"longitude":@"-80.27243212",@"name":@"Miami, FL"},
      @"44":@{@"latitude":@"38.57588764",@"longitude":@"-121.4702171",@"name":@"Sacramento, CA"},
      @"45":@{@"latitude":@"47.59857553",@"longitude":@"-122.3313301",@"name":@"Seattle, WA"},
      @"46":@{@"latitude":@"34.04280427",@"longitude":@"-118.2965074",@"name":@"Los Angeles, CA"},
      @"47":@{@"latitude":@"41.46452418",@"longitude":@"-81.67393711",@"name":@"Cleveland, OH"},
      @"48":@{@"latitude":@"42.34381556",@"longitude":@"-71.071416",@"name":@"Boston, MA"},
      @"49":@{@"latitude":@"43.66947253",@"longitude":@"-70.26322887",@"name":@"Portland, ME"},
      @"50":@{@"latitude":@"39.31090554",@"longitude":@"-76.61801497",@"name":@"Baltimore, MD"},
      @"51":@{@"latitude":@"39.10330504",@"longitude":@"-94.56236777",@"name":@"Kansas City, MO"},
      @"52":@{@"latitude":@"28.52060082",@"longitude":@"-81.33016169",@"name":@"Orlando, FL"},
      @"53":@{@"latitude":@"32.77477446",@"longitude":@"-117.1351335",@"name":@"San Diego, CA"},
      @"54":@{@"latitude":@"39.15543069",@"longitude":@"-84.49713303",@"name":@"Cincinnati, OH"},
      @"55":@{@"latitude":@"35.11794446",@"longitude":@"-89.95765669",@"name":@"Memphis, TN"},
      @"56":@{@"latitude":@"39.7964783",@"longitude":@"-86.15219582",@"name":@"Indianapolis, IN"}
    };
    
    NSDictionary *userTypes = @{
                                @"1": @"Recruiter",
                                @"2": @"Job Seeker"
                                };
    
    NSDictionary *jobTitles = @{
                                @"1": @"Able Seamen",
                                @"2": @"Account Manager",
                                @"3": @"Accountant",
                                @"4": @"Actor",
                                @"5": @"Actuary",
                                @"6": @"Adjustment Clerk",
                                @"8": @"Administrative Law Judge",
                                @"9": @"Administrative Services Manager",
                                @"10": @"Administrative Support Supervisors",
                                @"11": @"Advertising Manager OR Promotions Manager",
                                @"12": @"Advertising Sales Agent",
                                @"13": @"Aerospace Engineer",
                                @"14": @"Agricultural Crop Farm Manager",
                                @"15": @"Agricultural Crop Worker",
                                @"16": @"Agricultural Engineer",
                                @"17": @"Agricultural Equipment Operator",
                                @"18": @"Agricultural Inspector",
                                @"19": @"Agricultural Manager",
                                @"20": @"Agricultural Product Grader Sorter",
                                @"21": @"Agricultural Sales Representative",
                                @"22": @"Agricultural Science Technician",
                                @"23": @"Agricultural Sciences Teacher",
                                @"24": @"Agricultural Technician",
                                @"25": @"Agricultural Worker",
                                @"26": @"Air Crew Member",
                                @"27": @"Air Crew Officer",
                                @"28": @"Air Traffic Controller",
                                @"29": @"Aircraft Assembler",
                                @"30": @"Aircraft Body Repairer",
                                @"31": @"Aircraft Cargo Handling Supervisor",
                                @"32": @"Aircraft Engine Specialist",
                                @"33": @"Aircraft Launch and Recovery Officer",
                                @"34": @"Aircraft Launch Specialist",
                                @"35": @"Aircraft Mechanics OR Aircraft Service Technician",
                                @"36": @"Aircraft Rigging Assembler",
                                @"37": @"Aircraft Structure Assemblers",
                                @"38": @"Airfield Operations Specialist",
                                @"39": @"Airframe Mechanic",
                                @"40": @"Airline Pilot OR Copilot OR Flight Engineer",
                                @"41": @"Algorithm Developer",
                                @"42": @"Alteration Tailor",
                                @"43": @"Ambulance Driver",
                                @"44": @"Amusement Attendant",
                                @"45": @"Anesthesiologist",
                                @"46": @"Animal Breeder",
                                @"47": @"Animal Care Workers",
                                @"48": @"Animal Control Worker",
                                @"49": @"Animal Husbandry Worker",
                                @"50": @"Animal Scientist",
                                @"51": @"Animal Trainer",
                                @"52": @"Annealing Machine Operator",
                                @"53": @"Announcer",
                                @"54": @"Answering Service",
                                @"55": @"Anthropologist",
                                @"56": @"Anthropologist OR Archeologist",
                                @"57": @"Anthropology Teacher",
                                @"58": @"Appliance Repairer",
                                @"59": @"Arbitrator",
                                @"60": @"Archeologist",
                                @"61": @"Architect",
                                @"62": @"Architectural Drafter",
                                @"63": @"Architectural Drafter OR Civil Drafter",
                                @"64": @"Architecture Teacher",
                                @"65": @"Archivist",
                                @"66": @"Armored Assault Vehicle Crew Member",
                                @"67": @"Armored Assault Vehicle Officer",
                                @"68": @"Art Director",
                                @"69": @"Art Teacher",
                                @"70": @"Artillery Officer",
                                @"71": @"Artillery Crew Member",
                                @"72": @"Artist",
                                @"73": @"Assembler",
                                @"74": @"Assessor",
                                @"75": @"Astronomer",
                                @"76": @"Athletes and Sports Competitor",
                                @"77": @"Athletic Trainer",
                                @"78": @"Atmospheric and Space Scientist",
                                @"79": @"Audio and Video Equipment Technician",
                                @"80": @"Audiologist",
                                @"81": @"Audio-Visual Collections Specialist",
                                @"82": @"Auditor",
                                @"83": @"Auditor",
                                @"84": @"Automatic Teller Machine Servicer",
                                @"85": @"Automotive Body Repairer",
                                @"86": @"Automotive Glass Installers",
                                @"87": @"Automotive Master Mechanic",
                                @"88": @"Automotive Mechanic",
                                @"89": @"Automotive Specialty Technician",
                                @"90": @"Automotive Technician",
                                @"91": @"Auxiliary Equipment Operator",
                                @"92": @"Aviation Inspector",
                                @"93": @"Avionics Technician",
                                @"94": @"Bailiff",
                                @"95": @"Baker",
                                @"96": @"Barber",
                                @"97": @"Bartender",
                                @"98": @"Bartender Helper",
                                @"99": @"Battery Repairer",
                                @"100": @"Bellhop",
                                @"101": @"Bench Jeweler",
                                @"102": @"Benefits Specialist",
                                @"103": @"Bicycle Repairer",
                                @"104": @"Bill and Account Collector",
                                @"105": @"Bindery Machine Operator",
                                @"106": @"Bindery Worker",
                                @"107": @"Biochemist",
                                @"108": @"Biochemist or Biophysicist",
                                @"109": @"Biological Science Teacher",
                                @"110": @"Biological Scientist",
                                @"111": @"Biological Technician",
                                @"112": @"Biologist",
                                @"113": @"Biomedical Engineer",
                                @"114": @"Biophysicist",
                                @"115": @"Board Of Directors",
                                @"116": @"Boat Builder and Shipwright",
                                @"117": @"Boiler Operator",
                                @"118": @"Boilermaker",
                                @"119": @"Bookbinder",
                                @"120": @"Bookkeeper",
                                @"121": @"Brake Machine Setter",
                                @"122": @"Brattice Builder",
                                @"123": @"Brazer",
                                @"124": @"Brazing Machine Operator",
                                @"125": @"Brickmason",
                                @"126": @"Bridge Tender OR Lock Tender",
                                @"127": @"Broadcast News Analyst",
                                @"128": @"Broadcast Technician",
                                @"129": @"Brokerage Clerk",
                                @"130": @"Budget Analyst",
                                @"131": @"Buffing and Polishing Operator",
                                @"132": @"Building Cleaning Worker",
                                @"133": @"Building Inspector",
                                @"134": @"Bulldozer Operator",
                                @"135": @"Bus Driver",
                                @"136": @"Business Development Manager",
                                @"137": @"Business Manager",
                                @"138": @"Business Operations Specialist",
                                @"139": @"Business Teacher",
                                @"140": @"Butcher",
                                @"141": @"Buyer",
                                @"142": @"Cabinetmaker",
                                @"143": @"Cafeteria Cook",
                                @"144": @"Calibration Technician OR Instrumentation Technician",
                                @"145": @"Camera Operator",
                                @"146": @"Camera Repairer",
                                @"147": @"Captain",
                                @"148": @"Caption Writer",
                                @"149": @"Cardiovascular Technologist",
                                @"150": @"Career Counselor",
                                @"151": @"Carpenter",
                                @"152": @"Carpenter Assembler and Repairer",
                                @"153": @"Carpet Installer",
                                @"154": @"Cartographer",
                                @"155": @"Cartoonist",
                                @"156": @"Carver",
                                @"157": @"Cashier",
                                @"158": @"Casting Machine Operator",
                                @"159": @"Casting Machine Set-Up Operator",
                                @"161": @"Ceiling Tile Installer",
                                @"162": @"Cement Mason and Concrete Finisher",
                                @"163": @"Central Office",
                                @"164": @"Central Office and PBX Installers",
                                @"165": @"Central Office Operator",
                                @"166": @"CEO",
                                @"167": @"CFO",
                                @"168": @"Chef",
                                @"169": @"Chemical Engineer",
                                @"170": @"Chemical Equipment Controller",
                                @"171": @"Chemical Equipment Operator",
                                @"172": @"Chemical Equipment Tender",
                                @"173": @"Chemical Plant Operator",
                                @"174": @"Chemical Technician",
                                @"175": @"Chemist",
                                @"176": @"Chemistry Teacher",
                                @"177": @"Child Care",
                                @"178": @"Child Care Worker",
                                @"179": @"Chiropractor",
                                @"180": @"Choreographer",
                                @"182": @"City Planning Aide",
                                @"183": @"Civil Drafter",
                                @"184": @"Civil Engineer",
                                @"185": @"Civil Engineering Technician",
                                @"186": @"Claims Adjuster",
                                @"187": @"Claims Examiner",
                                @"188": @"Claims Taker",
                                @"189": @"Cleaners of Vehicles",
                                @"190": @"Clergy",
                                @"191": @"Clerk",
                                @"192": @"Clinical Laboratory Technician",
                                @"193": @"Clinical Psychologist",
                                @"194": @"Clinical School Psychologist",
                                @"195": @"Coaches and Scout",
                                @"196": @"Coating Machine Operator",
                                @"197": @"Coil Winders",
                                @"198": @"Command Control Center Officer",
                                @"199": @"Command Control Center Specialist",
                                @"200": @"Commercial and Industrial Designer",
                                @"201": @"Commercial Diver",
                                @"202": @"Commercial Pilot",
                                @"203": @"Communication Equipment Repairer",
                                @"204": @"Communication Equipment Worker",
                                @"205": @"Communications Equipment Operator",
                                @"206": @"Communications Teacher",
                                @"207": @"Community Service Manager",
                                @"208": @"Compacting Machine Operator",
                                @"209": @"Compensation and Benefits Manager",
                                @"210": @"Compliance Officers",
                                @"211": @"Composer",
                                @"213": @"Computer Hardware Engineer",
                                @"214": @"Computer Operator",
                                @"215": @"Computer Programmer",
                                @"216": @"Computer Repairer",
                                @"217": @"Computer Science Teacher",
                                @"218": @"Computer Scientist",
                                @"219": @"Computer Security Specialist",
                                @"220": @"Computer Software Engineer",
                                @"221": @"Computer Specialist",
                                @"222": @"Computer Support Specialist",
                                @"223": @"Computer Systems Analyst",
                                @"224": @"Computer-Controlled Machine Tool Operator",
                                @"225": @"Concierge",
                                @"226": @"Conservation Scientist",
                                @"228": @"Construction Carpenter",
                                @"229": @"Construction Driller",
                                @"230": @"Construction Equipment Operator",
                                @"231": @"Construction Laborer",
                                @"232": @"Construction Manager",
                                @"233": @"Continuous Mining Machine Operator",
                                @"234": @"Control Valve Installer",
                                @"235": @"Conveyor Operator",
                                @"236": @"Cook",
                                @"237": @"Cooling and Freezing Equipment Operator",
                                @"238": @"Copy Machine Operator",
                                @"239": @"Copy Writer",
                                @"240": @"Coremaking Machine Operator",
                                @"241": @"Coroner",
                                @"242": @"Corporate Trainer",
                                @"243": @"Correctional Officer",
                                @"244": @"Correspondence Clerk",
                                @"245": @"Cost Estimator",
                                @"246": @"Costume Attendant",
                                @"247": @"Counseling Psychologist",
                                @"248": @"Counselor",
                                @"249": @"Counsil",
                                @"250": @"Courier",
                                @"251": @"Court Clerk",
                                @"252": @"Court Reporter",
                                @"253": @"Craft Artist",
                                @"254": @"Crane and Tower Operator",
                                @"255": @"Creative Writer",
                                @"256": @"Credit Checkers Clerk",
                                @"257": @"Credit Analyst",
                                @"258": @"Credit Authorizer",
                                @"259": @"Credit Checker",
                                @"260": @"Criminal Investigator",
                                @"261": @"Crossing Guard",
                                @"262": @"Crushing Grinding Machine Operator",
                                @"263": @"CSI",
                                @"264": @"CTO",
                                @"265": @"Cultural Studies Teacher",
                                @"266": @"Curator",
                                @"267": @"Custom Tailor",
                                @"268": @"Customer Service Representative",
                                @"269": @"Cutting Machine Operator",
                                @"270": @"Cutting Machine Operator",
                                @"271": @"Dancer",
                                @"272": @"Data Entry Operator",
                                @"273": @"Data Processing Equipment Repairer",
                                @"274": @"Database Administrator",
                                @"275": @"Database Manager",
                                @"276": @"Deburring Machine Operator",
                                @"277": @"Decorator",
                                @"278": @"Dental Assistant",
                                @"279": @"Dental Hygienist",
                                @"280": @"Dental Laboratory Technician",
                                @"281": @"Dentist",
                                @"282": @"Designer",
                                @"283": @"Desktop Publisher",
                                @"284": @"Detective",
                                @"285": @"Diagnostic Medical Sonographer",
                                @"286": @"Diamond Worker",
                                @"287": @"Diesel Engine Specialist",
                                @"288": @"Dietetic Technician",
                                @"289": @"Director Of Business Development",
                                @"290": @"Director Of Marketing",
                                @"291": @"Director Of Social Media Marketing",
                                @"292": @"Director Of Talent Acquisition",
                                @"293": @"Director Religious Activities",
                                @"294": @"Directory Assistance Operator",
                                @"295": @"Dishwasher",
                                @"296": @"Dispatcher",
                                @"297": @"Distribution Manager",
                                @"298": @"Door To Door Sales",
                                @"299": @"Dot Etcher",
                                @"300": @"Drafter",
                                @"301": @"Dragline Operator",
                                @"302": @"Dredge Operator",
                                @"303": @"Drilling and Boring Machine Tool Setter",
                                @"304": @"Driver-Sales Worker",
                                @"305": @"Drycleaning Machine Operator",
                                @"306": @"Drywall Ceiling Tile Installer",
                                @"307": @"Drywall Installer",
                                @"308": @"Earth Driller",
                                @"309": @"Economics Teacher",
                                @"310": @"Economist",
                                @"311": @"Editor",
                                @"312": @"Education Administrator",
                                @"313": @"Education Teacher",
                                @"314": @"Educational Counselor OR Vocationall Counselor",
                                @"315": @"Educational Psychologist",
                                @"316": @"Electric Meter Installer",
                                @"317": @"Electric Motor Repairer",
                                @"318": @"Electrical and Electronic Inspector and Tester",
                                @"319": @"Electrical and Electronics Drafter",
                                @"320": @"Electrical Drafter",
                                @"321": @"Electrical Engineer",
                                @"322": @"Electrical Engineering Technician",
                                @"323": @"Electrical Parts Reconditioner",
                                @"324": @"Electrical Power-Line Installer",
                                @"325": @"Electrical Sales Representative",
                                @"326": @"Electrician",
                                @"327": @"Electrician",
                                @"328": @"Electrolytic Plating Machine Operator",
                                @"329": @"Electromechanical Equipment Assembler",
                                @"330": @"Electro-Mechanical Technician",
                                @"331": @"Electronic Drafter",
                                @"332": @"Electronic Engineering Technician",
                                @"333": @"Electronic Equipment Assembler",
                                @"334": @"Electronic Masking System Operator",
                                @"335": @"Electronics Engineer",
                                @"336": @"Electronics Engineering Technician",
                                @"337": @"Electrotyper",
                                @"338": @"Elementary and Secondary School Administrators",
                                @"339": @"Elementary School Teacher",
                                @"340": @"Elevator Installer and Repairer",
                                @"341": @"Eligibility Interviewer",
                                @"342": @"Embalmer",
                                @"343": @"Embossing Machine Operator",
                                @"344": @"Emergency Management Specialist",
                                @"345": @"Emergency Medical Technician and Paramedic",
                                @"346": @"Employment Interviewer",
                                @"347": @"Engine Assembler",
                                @"348": @"Engineer",
                                @"349": @"Engineering",
                                @"350": @"Engineering Manager",
                                @"351": @"Engineering Teacher",
                                @"352": @"Engineering Technician",
                                @"353": @"English Language Teacher",
                                @"354": @"Engraver",
                                @"355": @"Entertainer and Performer",
                                @"356": @"Entertainment Attendant",
                                @"357": @"Environmental Compliance Inspector",
                                @"358": @"Environmental Engineer",
                                @"359": @"Environmental Engineering Technician",
                                @"360": @"Environmental Science Teacher",
                                @"361": @"Environmental Science Technician",
                                @"362": @"Environmental Scientist",
                                @"363": @"Epidemiologist",
                                @"364": @"Equal Opportunity Representative",
                                @"365": @"Etcher",
                                @"366": @"Etcher and Engraver",
                                @"367": @"Event Planner",
                                @"368": @"Excavating Machine Operator",
                                @"369": @"Executive Secretary",
                                @"370": @"Exhibit Designer",
                                @"371": @"Explosives Expert",
                                @"372": @"Extraction Worker",
                                @"373": @"Extruding and Drawing Machine Operator",
                                @"374": @"Extruding Machine Operator",
                                @"375": @"Fabric Mender",
                                @"376": @"Fabric Pressers",
                                @"377": @"Farm and Home Management Advisor",
                                @"378": @"Farm Equipment Mechanic",
                                @"379": @"Farm Labor Contractor",
                                @"380": @"Farmer",
                                @"381": @"Farmworker",
                                @"382": @"Fashion Designer",
                                @"383": @"Fashion Model",
                                @"384": @"Fast Food Cook",
                                @"385": @"Fence Erector",
                                @"386": @"Fiber Product Cutting Machine Operator",
                                @"387": @"Fiberglass Laminator and Fabricator",
                                @"388": @"File Clerk",
                                @"389": @"Film Laboratory Technician",
                                @"390": @"Financial Analyst",
                                @"391": @"Financial Examiner",
                                @"392": @"Financial Manager",
                                @"393": @"Financial Services Sales Agent",
                                @"394": @"Financial Specialist",
                                @"395": @"Fire Fighter",
                                @"396": @"Fire Inspector",
                                @"397": @"Fire Investigator",
                                @"398": @"Fire-Prevention Engineer",
                                @"399": @"First-Line Supervisor-Manager of Landscaping",
                                @"400": @"Fish Game Warden",
                                @"401": @"Fish Hatchery Manager",
                                @"402": @"Fishery Worker",
                                @"403": @"Fishing OR Forestry Supervisor",
                                @"404": @"Fitness Trainer",
                                @"405": @"Fitter",
                                @"406": @"Flight Attendant",
                                @"407": @"Floor Finisher",
                                @"408": @"Floor Layer",
                                @"409": @"Floral Designer",
                                @"410": @"Food Batchmaker",
                                @"411": @"Food Cooking Machine Operators",
                                @"412": @"Food Preparation",
                                @"413": @"Food Preparation and Serving Worker",
                                @"414": @"Food Preparation Worker",
                                @"415": @"Food Science Technician",
                                @"416": @"Food Scientists and Technologist",
                                @"417": @"Food Servers",
                                @"418": @"Food Service Manager",
                                @"419": @"Food Tobacco Roasting",
                                @"420": @"Foreign Language Teacher",
                                @"421": @"Forensic Investigator",
                                @"422": @"Forensic Science Technician",
                                @"423": @"Forest and Conservation Technician",
                                @"424": @"Forest and Conservation Worker",
                                @"425": @"Forest Fire Fighter",
                                @"426": @"Forest Fire Fighting Supervisor",
                                @"427": @"Forest Fire Inspector",
                                @"428": @"Forester",
                                @"429": @"Forestry Conservation Science Teacher",
                                @"430": @"Forging Machine Setter",
                                @"431": @"Forming Machine Operator",
                                @"432": @"Forming Machine Operator",
                                @"433": @"Foundry Mold and Coremaker",
                                @"434": @"Fraud Investigator",
                                @"435": @"Freight Agent",
                                @"436": @"Freight and Material Mover",
                                @"437": @"Freight Inspector",
                                @"438": @"Funeral Attendant",
                                @"439": @"Funeral Director",
                                @"440": @"Furnace Operator",
                                @"441": @"Furniture Finisher",
                                @"442": @"Gaming Cage Worker",
                                @"443": @"Gaming Dealer",
                                @"444": @"Gaming Manager",
                                @"445": @"Gaming Service Worker",
                                @"446": @"Gaming Supervisor",
                                @"447": @"Gaming Surveillance Officer",
                                @"448": @"Garment",
                                @"449": @"Gas Appliance Repairer",
                                @"450": @"Gas Compressor Operator",
                                @"451": @"Gas Distribution Plant Operator",
                                @"452": @"Gas Plant Operator",
                                @"453": @"Gas Processing Plant Operator",
                                @"454": @"Gas Pumping Station Operator",
                                @"455": @"Gas Pumping Station Operator",
                                @"456": @"Gauger",
                                @"457": @"GED Teacher",
                                @"458": @"General Farmworker",
                                @"459": @"General Manager",
                                @"460": @"General Practitioner",
                                @"461": @"Geographer",
                                @"462": @"Geography Teacher",
                                @"463": @"Geological Data Technician",
                                @"464": @"Geological Sample Test Technician",
                                @"465": @"Geologist",
                                @"466": @"Geoscientists",
                                @"467": @"Glass Blower",
                                @"468": @"Glass Cutting Machine Operator",
                                @"469": @"Glazier",
                                @"470": @"Gluing Machine Operator",
                                @"471": @"Government",
                                @"472": @"Government Property Inspector",
                                @"473": @"Government Service Executive",
                                @"474": @"Graduate Teaching Assistant",
                                @"475": @"Graphic Designer",
                                @"476": @"Grinder OR Polisher",
                                @"477": @"Grinding Machine Operator",
                                @"478": @"Grips",
                                @"479": @"Grounds Maintenance Worker",
                                @"480": @"Hairdresser OR Cosmetologist",
                                @"481": @"Hand Trimmer",
                                @"482": @"Hand Presser",
                                @"483": @"Hand Sewer",
                                @"484": @"Hazardous Materials Removal Worker",
                                @"485": @"Head Nurse",
                                @"486": @"Health Educator",
                                @"487": @"Health Practitioner",
                                @"488": @"Health Services Manager",
                                @"489": @"Health Specialties Teacher",
                                @"490": @"Health Technologist",
                                @"491": @"Healthcare",
                                @"492": @"Healthcare Practitioner",
                                @"493": @"Healthcare Support Worker",
                                @"494": @"Heat Treating Equipment Operator",
                                @"495": @"Heaters",
                                @"496": @"Heating and Air Conditioning Mechanic",
                                @"497": @"Heating Equipment Operator",
                                @"498": @"Heavy Equipment Mechanic",
                                @"499": @"Highway Maintenance Worker",
                                @"500": @"Highway Patrol Pilot",
                                @"501": @"Historian",
                                @"502": @"History Teacher",
                                @"503": @"Hoist and Winch Operator",
                                @"504": @"Home",
                                @"505": @"Home Appliance Installer",
                                @"506": @"Home Appliance Repairer",
                                @"507": @"Home Economics Teacher",
                                @"508": @"Home Entertainment Equipment Installer",
                                @"509": @"Home Health Aide",
                                @"510": @"Homeland Security",
                                @"511": @"Horticultural Worker",
                                @"512": @"Host and Hostess",
                                @"513": @"Hotel Desk Clerk",
                                @"514": @"House Cleaner",
                                @"515": @"Housekeeper",
                                @"516": @"Housekeeping Supervisor",
                                @"517": @"HR Manager",
                                @"518": @"HR Specialist",
                                @"519": @"Human Resource Director",
                                @"520": @"Human Resource Manager",
                                @"521": @"Human Resources Assistant",
                                @"522": @"Human Resources Manager",
                                @"523": @"Human Resources Specialist",
                                @"524": @"Hunter and Trapper",
                                @"525": @"HVAC Mechanic",
                                @"526": @"Hydrologist",
                                @"527": @"Illustrator",
                                @"528": @"Immigration Inspector OR Customs Inspector",
                                @"529": @"Industrial Engineer",
                                @"530": @"Industrial Engineering Technician",
                                @"531": @"Industrial Equipment Maintenance",
                                @"532": @"Industrial Machinery Mechanic",
                                @"533": @"Industrial Production Manager",
                                @"534": @"Industrial Safety Engineer",
                                @"535": @"Industrial-Organizational Psychologist",
                                @"536": @"Infantry",
                                @"537": @"Infantry Officer",
                                @"538": @"Information Systems Manager",
                                @"539": @"Inspector",
                                @"540": @"Installation and Repair Technician",
                                @"541": @"Instructional Coordinator",
                                @"542": @"Instrument Sales Representative",
                                @"543": @"Insulation Installer",
                                @"544": @"Insulation Worker",
                                @"545": @"Insurance Investigator",
                                @"546": @"Insurance Appraiser",
                                @"547": @"Insurance Claims Clerk",
                                @"548": @"Insurance Policy Processing Clerk",
                                @"549": @"Insurance Sales Agent",
                                @"550": @"Insurance Underwriter",
                                @"551": @"Interaction Designer",
                                @"552": @"Interior Designer",
                                @"553": @"Internist",
                                @"554": @"Interpreter OR Translator",
                                @"555": @"Interviewer",
                                @"556": @"Irradiated-Fuel Handler",
                                @"557": @"Janitor",
                                @"558": @"Janitorial Supervisor",
                                @"559": @"Jeweler",
                                @"560": @"Jewelry Model OR Mold Makers",
                                @"561": @"Job Printer",
                                @"562": @"Judge",
                                @"563": @"Keyboard Instrument Repairer and Tuner",
                                @"564": @"Kindergarten Teacher",
                                @"565": @"Landscape Architect",
                                @"566": @"Landscape Artist",
                                @"567": @"Landscaper",
                                @"568": @"Landscaping",
                                @"569": @"Lathe Operator",
                                @"570": @"Laundry OR Dry-Cleaning Worker",
                                @"571": @"Law Clerk",
                                @"572": @"Law Enforcement Teacher",
                                @"573": @"Law Teacher",
                                @"574": @"Lawn Service Manager",
                                @"575": @"Lawyer",
                                @"576": @"Lay-Out Worker",
                                @"577": @"Legal Secretary",
                                @"578": @"Legal Support Worker",
                                @"579": @"Legislator",
                                @"580": @"Letterpress Setters Operator",
                                @"581": @"Librarian",
                                @"582": @"Library Assistant",
                                @"583": @"Library Science Teacher",
                                @"584": @"Library Technician",
                                @"585": @"Library Worker",
                                @"586": @"License Clerk",
                                @"587": @"Licensed Practical Nurse",
                                @"588": @"Licensing Examiner and Inspector",
                                @"589": @"Life Science Technician",
                                @"590": @"Life Scientists",
                                @"591": @"Lifeguard",
                                @"592": @"Loading Machine Operator",
                                @"593": @"Loan Counselor",
                                @"594": @"Loan Interviewer",
                                @"595": @"Loan Officer",
                                @"596": @"Locker Room Attendant",
                                @"597": @"Locksmith",
                                @"598": @"Locomotive Engineer",
                                @"599": @"Locomotive Firer",
                                @"600": @"Lodging Manager",
                                @"601": @"Log Grader and Scaler",
                                @"602": @"Logging Equipment Operator",
                                @"603": @"Logging Supervisor",
                                @"604": @"Logging Tractor Operator",
                                @"605": @"Logging Worker",
                                @"606": @"Logistician",
                                @"607": @"Machine Feeder",
                                @"608": @"Machine Operator",
                                @"609": @"Machine Tool Operator",
                                @"610": @"Machinery Maintenance",
                                @"611": @"Machinist",
                                @"612": @"Maid",
                                @"613": @"Mail Clerk",
                                @"614": @"Mail Machine Operator",
                                @"615": @"Maintenance and Repair Worker",
                                @"616": @"Maintenance Equipment Operator",
                                @"617": @"Maintenance Supervisor",
                                @"618": @"Maintenance Worker",
                                @"619": @"Makeup Artists",
                                @"620": @"Management Analyst",
                                @"621": @"Manager",
                                @"622": @"Manager of Air Crew",
                                @"623": @"Manager of Food Preparation",
                                @"624": @"Manager of Weapons Specialists",
                                @"625": @"Manager Tactical Operations",
                                @"626": @"Manicurists",
                                @"627": @"Manufactured Building Installer",
                                @"628": @"Manufacturing Sales Representative",
                                @"629": @"Mapping Technician",
                                @"630": @"MARCOM Director",
                                @"631": @"MARCOM Manager",
                                @"632": @"Marine Architect",
                                @"633": @"Marine Cargo Inspector",
                                @"634": @"Marine Engineer",
                                @"635": @"Marine Oiler",
                                @"636": @"Market Research Analyst",
                                @"637": @"Marketing Manager",
                                @"638": @"Marketing VP",
                                @"639": @"Marking Clerk",
                                @"640": @"Marking Machine Operator",
                                @"641": @"Marriage and Family Therapist",
                                @"642": @"Massage Therapist",
                                @"643": @"Material Movers",
                                @"644": @"Material Moving Worker",
                                @"645": @"Materials Engineer",
                                @"646": @"Materials Inspector",
                                @"647": @"Materials Scientist",
                                @"648": @"Mathematical Science Teacher",
                                @"649": @"Mathematical Scientist",
                                @"650": @"Mathematical Technician",
                                @"651": @"Mathematician",
                                @"652": @"Meat Packer",
                                @"653": @"Mechanical Door Repairer",
                                @"654": @"Mechanical Drafter",
                                @"655": @"Mechanical Engineer",
                                @"656": @"Mechanical Engineering Technician",
                                @"657": @"Mechanical Equipment Sales Representative",
                                @"658": @"Mechanical Inspector",
                                @"659": @"Media and Communication Worker",
                                @"660": @"Medical Appliance Technician",
                                @"661": @"Medical Assistant",
                                @"662": @"Medical Equipment Preparer",
                                @"663": @"Medical Equipment Repairer",
                                @"664": @"Medical Laboratory Technologist",
                                @"665": @"Medical Records Technician",
                                @"666": @"Medical Sales Representative",
                                @"667": @"Medical Scientists",
                                @"668": @"Medical Secretary",
                                @"669": @"Medical Technician",
                                @"670": @"Medical Transcriptionist",
                                @"671": @"Mental Health Counselor",
                                @"672": @"Merchandise Displayer OR Window Trimmer",
                                @"673": @"Metal Fabricator",
                                @"674": @"Metal Molding Operator",
                                @"675": @"Metal Pourer and Caster",
                                @"676": @"Metal Worker",
                                @"677": @"Metal-Refining Furnace Operator",
                                @"678": @"Meter Mechanic",
                                @"679": @"Microbiologist",
                                @"680": @"Middle School Teacher",
                                @"681": @"Military Officer",
                                @"682": @"Milling Machine Operator",
                                @"683": @"Millwright",
                                @"684": @"Mine Cutting Machine Operator",
                                @"685": @"Mining Engineer OR Geological Engineer",
                                @"686": @"Mining Machine Operator",
                                @"687": @"Mixing and Blending Machine Operator",
                                @"688": @"Model Maker",
                                @"689": @"Mold Maker",
                                @"690": @"Molder",
                                @"691": @"Molding and Casting Worker",
                                @"692": @"Molding Machine Operator",
                                @"693": @"Motion Picture Projectionist",
                                @"694": @"Motor Vehicle Inspector",
                                @"695": @"Motor Vehicle Operator",
                                @"696": @"Motorboat Mechanic",
                                @"697": @"Motorboat Operator",
                                @"698": @"Motorcycle Mechanic",
                                @"699": @"Movers",
                                @"700": @"Movie Director oR Theatre Director",
                                @"701": @"Multi-Media Artist",
                                @"702": @"Multiple Machine Tool Setter",
                                @"703": @"Municipal Clerk",
                                @"704": @"Municipal Court Clerk",
                                @"705": @"Municipal Fire Fighter",
                                @"706": @"Municipal Fire Fighting Supervisor",
                                @"707": @"Museum Conservator",
                                @"708": @"Music Arranger and Orchestrator",
                                @"709": @"Music Composer",
                                @"710": @"Music Director",
                                @"711": @"Musical Instrument Tuner",
                                @"712": @"Musician",
                                @"713": @"Musician OR Singer",
                                @"714": @"Natural Sciences Manager",
                                @"715": @"Naval Architects",
                                @"716": @"Network Admin OR Computer Systems Administrator",
                                @"717": @"Network Systems Analyst",
                                @"718": @"New Accounts Clerk",
                                @"719": @"Night Security Guard",
                                @"720": @"Night Shift",
                                @"721": @"Nonfarm Animal Caretaker",
                                @"722": @"Nuclear Engineer",
                                @"723": @"Nuclear Equipment Operation Technician",
                                @"724": @"Nuclear Medicine Technologist",
                                @"725": @"Nuclear Monitoring Technician",
                                @"726": @"Nuclear Power Reactor Operator",
                                @"727": @"Nuclear Technician",
                                @"728": @"Numerical Control Machine Tool Operator",
                                @"729": @"Numerical Tool Programmer OR Process Control Programmer",
                                @"730": @"Nursery Manager",
                                @"731": @"Nursery Worker",
                                @"732": @"Nursing Aide",
                                @"733": @"Nursing Instructor",
                                @"734": @"Nutritionist",
                                @"735": @"Obstetrician",
                                @"736": @"Occupational Health Safety Specialist",
                                @"737": @"Occupational Health Safety Technician",
                                @"738": @"Occupational Therapist",
                                @"739": @"Occupational Therapist Aide",
                                @"740": @"Occupational Therapist Assistant",
                                @"741": @"Office and Administrative Support Worker",
                                @"742": @"Office Clerk",
                                @"743": @"Office Machine and Cash Register Servicer",
                                @"744": @"Office Machine Operator",
                                @"745": @"Offset Lithographic Press Operator",
                                @"746": @"Oil and gas Operator",
                                @"747": @"Oil Service Unit Operator",
                                @"748": @"Online Marketing Analyst",
                                @"749": @"Operating Engineer",
                                @"750": @"Operations Research Analyst",
                                @"751": @"Ophthalmic Laboratory Technician",
                                @"752": @"Optical Instrument Assembler",
                                @"753": @"Opticians",
                                @"754": @"Optometrist",
                                @"755": @"Oral Surgeon",
                                @"756": @"Order Clerk",
                                @"757": @"Order Filler",
                                @"758": @"Order Filler OR Stock Clerk",
                                @"759": @"Organizational Development Manager",
                                @"760": @"Orthodontist",
                                @"761": @"Orthotist OR Prosthetist",
                                @"762": @"Outdoor Power Equipment Mechanic",
                                @"763": @"Packaging Machine Operator",
                                @"764": @"Packer and Packager",
                                @"765": @"Painter",
                                @"766": @"Painter and Illustrator",
                                @"767": @"Painting Machine Operator",
                                @"768": @"Pantograph Engraver",
                                @"769": @"Paper Goods Machine Operator",
                                @"770": @"Paperhanger",
                                @"771": @"Paralegal",
                                @"772": @"Park Naturalist",
                                @"773": @"Parking Enforcement Worker",
                                @"774": @"Parking Lot Attendant",
                                @"775": @"Parts Salesperson",
                                @"776": @"Paste-Up Worker",
                                @"777": @"Pastry Chef",
                                @"778": @"Patrol Officer",
                                @"779": @"Patternmaker",
                                @"780": @"Paving Equipment Operator",
                                @"781": @"Payroll Clerk",
                                @"782": @"Pediatricians",
                                @"783": @"Percussion Instrument Repairer",
                                @"784": @"Personal Care Worker",
                                @"785": @"Personal Financial Advisor",
                                @"786": @"Personal Home Care Aide",
                                @"787": @"Personal Service Worker",
                                @"788": @"Personal Trainer",
                                @"789": @"Personnel Recruiter",
                                @"790": @"Pest Control Worker",
                                @"791": @"Pesticide Sprayer",
                                @"792": @"Petroleum Engineer",
                                @"793": @"Petroleum Pump Operator",
                                @"794": @"Petroleum Pump System Operator",
                                @"795": @"Petroleum Technician",
                                @"796": @"Pewter Caster",
                                @"797": @"Pharmaceutical Sales Representative",
                                @"798": @"Pharmacist",
                                @"799": @"Pharmacy Aide",
                                @"800": @"Pharmacy Technician",
                                @"801": @"Philosophy and Religion Teacher",
                                @"802": @"Photoengraver",
                                @"803": @"Photoengraving Machine Operator",
                                @"804": @"Photographer",
                                @"805": @"Photographic Restorer",
                                @"806": @"Photographic Developer",
                                @"807": @"Photographic Process Worker",
                                @"808": @"Photographic Processing Machine Operator",
                                @"809": @"Photographic Reproduction Technician",
                                @"810": @"Physical Scientist",
                                @"811": @"Physical Therapist",
                                @"812": @"Physical Therapist Aide",
                                @"813": @"Physical Therapist Assistant",
                                @"814": @"Physician",
                                @"815": @"Physician Assistant",
                                @"816": @"Physicist",
                                @"817": @"Physics Teacher",
                                @"818": @"Pile-Driver Operator",
                                @"819": @"Pipe Fitter",
                                @"820": @"Pipefitter",
                                @"821": @"Pipelayer",
                                @"822": @"Pipelaying Fitter",
                                @"823": @"Plant and System Operator",
                                @"824": @"Plant Scientist",
                                @"825": @"Plasterer OR Stucco Mason",
                                @"826": @"Plastic Molding Machine Operator",
                                @"827": @"Plate Finisher",
                                @"828": @"Platemaker",
                                @"829": @"Plating Machine Operator",
                                @"830": @"Plating Operator",
                                @"831": @"Plating Operator OR Coating Machine Operator",
                                @"832": @"Plumber",
                                @"833": @"Plumber OR Pipefitter OR Steamfitter",
                                @"834": @"Podiatrist",
                                @"835": @"Poet OR Lyricist",
                                @"836": @"Police and Sheriffs Patrol Officer",
                                @"837": @"Police Detective",
                                @"838": @"Police Identification OR Records Officer",
                                @"839": @"Political Science Teacher",
                                @"840": @"Political Scientist",
                                @"841": @"Portable Power Tool Repairer",
                                @"842": @"Postal Clerk",
                                @"843": @"Postal Service Clerk",
                                @"844": @"Postal Service Mail Carrier",
                                @"845": @"Postal Service Mail Sorter",
                                @"846": @"Postmasters",
                                @"847": @"Postsecondary Education Administrators",
                                @"848": @"Postsecondary Teacher",
                                @"849": @"Potter",
                                @"850": @"Poultry Cutter",
                                @"851": @"Power Distributors OR Dispatcher",
                                @"852": @"Power Generating Plant Operator",
                                @"853": @"Power Plant Operator",
                                @"854": @"PR Manager",
                                @"855": @"Precious Stone Worker",
                                @"856": @"Precision Aircraft Systems Assemblers",
                                @"857": @"Precision Devices Inspector",
                                @"858": @"Precision Dyer",
                                @"859": @"Precision Etcher and Engraver",
                                @"860": @"Precision Instrument Repairer",
                                @"861": @"Precision Lens Grinders and Polisher",
                                @"862": @"Precision Mold and Pattern Caster",
                                @"863": @"Precision Pattern and Die Caster",
                                @"864": @"Precision Printing Worker",
                                @"865": @"Prepress Technician",
                                @"866": @"Preschool Education Administrators",
                                @"867": @"Preschool Teacher",
                                @"868": @"Press Machine Setter",
                                @"869": @"Pressing Machine Operator",
                                @"870": @"Pressure Vessel Inspector",
                                @"871": @"Printing Machine Operator",
                                @"872": @"Printing Press Machine Operator",
                                @"873": @"Private Detective and Investigator",
                                @"874": @"Private Household Cook",
                                @"875": @"Private Sector Executive",
                                @"876": @"Probation Officers and Correctional Treatment Specialist",
                                @"877": @"Procurement Clerk",
                                @"878": @"Producer",
                                @"879": @"Producers and Director",
                                @"880": @"Product Management Leader",
                                @"881": @"Product Promoter",
                                @"882": @"Product Safety Engineer",
                                @"883": @"Product Specialist",
                                @"884": @"Production Control Manager",
                                @"885": @"Production Helper",
                                @"886": @"Production Inspector",
                                @"887": @"Production Laborer",
                                @"888": @"Production Manager",
                                @"889": @"Production Planner",
                                @"890": @"Production Planning",
                                @"891": @"Production Worker",
                                @"892": @"Professional Photographer",
                                @"893": @"Professor",
                                @"894": @"Program Director",
                                @"895": @"Project Manager",
                                @"896": @"Proofreaders and Copy Marker",
                                @"897": @"Prosthodontist",
                                @"898": @"Protective Service Worker",
                                @"899": @"Protective Service Worker",
                                @"900": @"Psychiatric Aide",
                                @"901": @"Psychiatric Technician",
                                @"902": @"Psychiatrist",
                                @"903": @"Psychologist",
                                @"904": @"Psychology Teacher",
                                @"905": @"Public Health Social Worker",
                                @"906": @"Public Relations Manager",
                                @"907": @"Public Relations Specialist",
                                @"908": @"Public Transportation Inspector",
                                @"909": @"Pump Operators",
                                @"910": @"Punching Machine Setters",
                                @"911": @"Purchasing Agent",
                                @"912": @"Purchasing Manager",
                                @"913": @"Radar Technician",
                                @"914": @"Radiation Therapist",
                                @"915": @"Radio and Television Announcer",
                                @"916": @"Radio Mechanic",
                                @"917": @"Radio Operator",
                                @"918": @"Radiologic Technician",
                                @"919": @"Radiologic Technologist",
                                @"920": @"Radiologic Technologist and Technician",
                                @"921": @"Rail Car Repairer",
                                @"922": @"Rail Transportation Worker",
                                @"923": @"Rail Yard Engineer",
                                @"924": @"Railroad Conductors",
                                @"925": @"Railroad Inspector",
                                @"926": @"Railroad Switch Operator",
                                @"927": @"Railroad Yard Worker",
                                @"928": @"Range Manager",
                                @"929": @"Real Estate Appraiser",
                                @"930": @"Real Estate Association Manager",
                                @"931": @"Real Estate Broker",
                                @"932": @"Real Estate Sales Agent",
                                @"933": @"Receptionist and Information Clerk",
                                @"934": @"Record Clerk",
                                @"935": @"Recordkeeping Clerk",
                                @"936": @"Recreation and Fitness Studies Teacher",
                                @"937": @"Recreation Worker",
                                @"938": @"Recreational Therapist",
                                @"939": @"Recreational Vehicle Service Technician",
                                @"940": @"Recruiter",
                                @"941": @"Recyclable Material Collector",
                                @"942": @"Refinery Operator",
                                @"943": @"Refractory Materials Repairer",
                                @"944": @"Refrigeration Mechanic",
                                @"945": @"Registered Nurse",
                                @"946": @"Rehabilitation Counselor",
                                @"947": @"Religious Worker",
                                @"948": @"Rental Clerk",
                                @"949": @"Reporters OR Correspondent",
                                @"950": @"Reservation Agent OR Transportation Ticket Agent",
                                @"951": @"Residential Advisor",
                                @"952": @"Respiratory Therapist",
                                @"953": @"Respiratory Therapy Technician",
                                @"954": @"Restaurant Cook",
                                @"955": @"Retail Sales person",
                                @"956": @"Retail Salesperson",
                                @"957": @"Rigger",
                                @"958": @"RN",
                                @"959": @"Rock Splitter",
                                @"960": @"Rolling Machine Setter",
                                @"961": @"Roof Bolters Mining",
                                @"962": @"Roofer",
                                @"963": @"Rotary Drill Operator",
                                @"964": @"Rough Carpenter",
                                @"965": @"Roustabouts",
                                @"966": @"Safety Engineer",
                                @"967": @"Sailor",
                                @"968": @"Sales and Related Workers",
                                @"969": @"Sales Engineer",
                                @"970": @"Sales Manager",
                                @"971": @"Sales Person",
                                @"972": @"Sales Representative",
                                @"973": @"Sawing Machine Operator",
                                @"974": @"Sawing Machine Setter",
                                @"975": @"Sawing Machine Tool Setter",
                                @"976": @"Scanner Operator",
                                @"977": @"School Bus Driver",
                                @"978": @"School Social Worker",
                                @"979": @"Scientific Photographer",
                                @"980": @"Screen Printing Machine Operator",
                                @"981": @"Sculptor",
                                @"982": @"Secondary School Teacher",
                                @"983": @"Secretary",
                                @"984": @"Securities Sales Agent",
                                @"985": @"Security Guard",
                                @"986": @"Security Systems Installer OR Fire Alarm Systems Installer",
                                @"987": @"Segmental Paver",
                                @"988": @"Self-Enrichment Education Teacher",
                                @"989": @"Semiconductor Processor",
                                @"990": @"Separating Machine Operators",
                                @"991": @"Septic Tank Servicer",
                                @"992": @"Service Station Attendant",
                                @"993": @"Set and Exhibit Designer",
                                @"994": @"Set Designer",
                                @"995": @"Sewing Machine Operator",
                                @"996": @"Shampooer",
                                @"997": @"Shear Machine Set-Up Operator",
                                @"998": @"Sheet Metal Worker",
                                @"999": @"Sheriff",
                                @"1000": @"Ship Captain",
                                @"1001": @"Ship Carpenter and Joiner",
                                @"1002": @"Ship Engineer",
                                @"1003": @"Ship Mates",
                                @"1004": @"Ship Pilot",
                                @"1005": @"Shipping and Receiving Clerk",
                                @"1006": @"Shoe and Leather Repairer",
                                @"1007": @"Shoe Machine Operators",
                                @"1008": @"Short Order Cook",
                                @"1009": @"Shuttle Car Operator",
                                @"1010": @"Signal Repairer OR Track Switch Repairer",
                                @"1011": @"Silversmith",
                                @"1012": @"Singer",
                                @"1013": @"Sketch Artist",
                                @"1014": @"Skin Care Specialist",
                                @"1015": @"Slot Key Person",
                                @"1016": @"Social and Human Service Assistant",
                                @"1017": @"Social Media Marketing Manager",
                                @"1018": @"Social Science Research Assistant",
                                @"1019": @"Social Sciences Teacher",
                                @"1020": @"Social Scientists",
                                @"1021": @"Social Service Specialists",
                                @"1022": @"Social Work Teacher",
                                @"1023": @"Social Worker",
                                @"1024": @"Sociologist",
                                @"1025": @"Sociology Teacher",
                                @"1026": @"Software Engineer",
                                @"1027": @"Soil Conservationist",
                                @"1028": @"Soil Scientist",
                                @"1029": @"Soil Scientist OR Plant Scientist",
                                @"1030": @"Solderer",
                                @"1031": @"Soldering Machine Setter",
                                @"1032": @"Sound Engineering Technician",
                                @"1033": @"Space Sciences Teacher",
                                @"1034": @"Special Education Teacher",
                                @"1035": @"Special Force",
                                @"1036": @"Special Forces Officer",
                                @"1037": @"Speech-Language Pathologist",
                                @"1038": @"Sports Book Writer",
                                @"1039": @"Spotters",
                                @"1040": @"Spraying Machine Operator",
                                @"1041": @"Staff Psychologist",
                                @"1042": @"State",
                                @"1043": @"Statement Clerk",
                                @"1044": @"Stationary Engineer",
                                @"1045": @"Stationary Engineer OR Boiler Operator",
                                @"1046": @"Statistical Assistant",
                                @"1047": @"Statistician",
                                @"1048": @"Steel Worker",
                                @"1049": @"Stevedore",
                                @"1050": @"Stock Broker",
                                @"1051": @"Stock Clerk",
                                @"1052": @"Stone Cutter",
                                @"1053": @"Stone Sawyer",
                                @"1054": @"Stonemason",
                                @"1056": @"Storage Manager OR Distribution Manager",
                                @"1057": @"Streetcar Operator",
                                @"1058": @"Stringed Instrument Repairer and Tuner",
                                @"1059": @"Stripper",
                                @"1060": @"Structural Iron and Steel Worker",
                                @"1061": @"Structural Metal Fabricator",
                                @"1062": @"Substance Abuse Counselor",
                                @"1063": @"Substance Abuse Social Worker",
                                @"1064": @"Substation Maintenance",
                                @"1065": @"Supervisor Correctional Officer",
                                @"1066": @"Supervisor Fire Fighting Worker",
                                @"1067": @"Supervisor of Customer Service",
                                @"1068": @"Supervisor of Police",
                                @"1069": @"Surgeon",
                                @"1070": @"Surgical Technologist",
                                @"1071": @"Survey Researcher",
                                @"1072": @"Surveying and Mapping Technician",
                                @"1073": @"Surveying Technician",
                                @"1074": @"Surveyor",
                                @"1076": @"System Administrator",
                                @"1077": @"Tailor",
                                @"1078": @"Talent Acquisition Manager",
                                @"1079": @"Talent Director",
                                @"1080": @"Tank Car",
                                @"1081": @"Taper",
                                @"1082": @"Tax Examiner",
                                @"1083": @"Tax Preparer",
                                @"1084": @"Taxi Drivers and Chauffeur",
                                @"1085": @"Teacher",
                                @"1086": @"Teacher Assistant",
                                @"1087": @"Team Assembler",
                                @"1088": @"Technical Director",
                                @"1089": @"Technical Program Manager",
                                @"1090": @"Technical Specialist",
                                @"1091": @"Technical Writer",
                                @"1092": @"Telecommunications Equipment Installer",
                                @"1093": @"Telecommunications Facility Examiner",
                                @"1094": @"Telecommunications Line Installer",
                                @"1095": @"Telemarketer",
                                @"1096": @"Telephone Operator",
                                @"1097": @"Telephone Station Installer and Repairer",
                                @"1098": @"Teller",
                                @"1099": @"Terrazzo Workes and Finisher",
                                @"1100": @"Textile Cutting Machine Operator",
                                @"1101": @"Textile Dyeing Machine Operator",
                                @"1102": @"Textile Knitting Machine Operator",
                                @"1103": @"Textile Machine Operator",
                                @"1104": @"Textile Worker",
                                @"1105": @"Therapist",
                                @"1106": @"Ticket Agent",
                                @"1107": @"Tile Setter OR Marble Setter",
                                @"1108": @"Timing Device Assemblers",
                                @"1109": @"Tire Builder",
                                @"1110": @"Tire Changer",
                                @"1111": @"Title Abstractor",
                                @"1112": @"Title Examiner",
                                @"1113": @"Title Searcher",
                                @"1114": @"Tool and Die Maker",
                                @"1115": @"Tool Set-Up Operator",
                                @"1116": @"Tool Sharpener",
                                @"1117": @"Tour Guide",
                                @"1118": @"Tractor Operator",
                                @"1119": @"Tractor-Trailer Truck Driver",
                                @"1120": @"Traffic Technician",
                                @"1121": @"Train Crew",
                                @"1122": @"Trainer",
                                @"1123": @"Training Manager OR Development Manager",
                                @"1124": @"Transformer Repairer",
                                @"1125": @"Transit Police OR Railroad Police",
                                @"1126": @"Transportation and Material-Moving",
                                @"1127": @"Transportation Attendant",
                                @"1128": @"Transportation Equipment Maintenance",
                                @"1129": @"Transportation Equipment Painters",
                                @"1130": @"Transportation Inspector",
                                @"1131": @"Transportation Manager",
                                @"1132": @"Transportation Worker",
                                @"1133": @"Travel Agent",
                                @"1134": @"Travel Clerk",
                                @"1135": @"Travel Guide",
                                @"1136": @"Tree Trimmer",
                                @"1137": @"Truck Driver",
                                @"1140": @"Typesetting Machine Operator",
                                @"1141": @"Umpire and Referee",
                                @"1142": @"Underground Mining",
                                @"1143": @"University",
                                @"1144": @"Upholsterer",
                                @"1145": @"Urban Planner",
                                @"1146": @"User Experience Manager",
                                @"1147": @"User Experience Researcher",
                                @"1148": @"Usher",
                                @"1149": @"Utility Meter Reader",
                                @"1150": @"Valve Repairer OR Regulator Repairer",
                                @"1151": @"Vending Machine Servicer",
                                @"1152": @"Veterinarian",
                                @"1153": @"Veterinary Assistant OR Laboratory Animal Caretaker",
                                @"1154": @"Veterinary Technician",
                                @"1155": @"Vice President Of Human Resources",
                                @"1156": @"Vice President Of Marketing",
                                @"1157": @"Video Editor",
                                @"1158": @"Visual Designer",
                                @"1159": @"Vocational Education Teacher",
                                @"1160": @"Waiter",
                                @"1161": @"Waitress",
                                @"1163": @"Washing Equipment Operator",
                                @"1164": @"Waste Treatment Plant Operator",
                                @"1165": @"Watch Repairer",
                                @"1166": @"Weapons Specialists",
                                @"1167": @"Web Developer",
                                @"1168": @"Webmaster",
                                @"1169": @"Welder",
                                @"1171": @"Welder and Cutter",
                                @"1172": @"Welder-Fitter",
                                @"1173": @"Welding Machine Tender",
                                @"1174": @"Welding Machine Operator",
                                @"1175": @"Welding Machine Setter",
                                @"1176": @"Welfare Eligibility Clerk",
                                @"1177": @"Well and Core Drill Operator",
                                @"1178": @"Wellhead Pumper",
                                @"1179": @"Wholesale Buyer",
                                @"1180": @"Wind Instrument Repairer",
                                @"1181": @"Woodworker",
                                @"1182": @"Woodworking Machine Operator",
                                @"1183": @"Woodworking Machine Setter",
                                @"1184": @"Word Processors and Typist",
                                @"1185": @"Writer OR Author",
                                @"1186": @"Zoologists OR Wildlife Biologist"
                                };
    
    NSDictionary *terms = [NSDictionary dictionaryWithObjectsAndKeys:
                           @"Part time", @"1",
                           @"Intern", @"2",
                           @"Temp", @"3",
                           @"Contract", @"4",
                           @"Contract to Hire", @"5",
                           @"Associate Degree", @"6",
                           @"Full Time", @"7",
                           nil];
    
    NSDictionary *degree = [NSDictionary dictionaryWithObjectsAndKeys:
                            @"Tap to Change", @"0",
                            @"Some High School Coursework", @"1",
                            @"High School", @"2",
                            @"Certification", @"3",
                            @"Vocational", @"4",
                            @"Some Colleage Coursework", @"5",
                            @"Associate Degree", @"6",
                            @"Bachelar's Degree", @"7",
                            @"Master's Degree", @"8",
                            @"Doctorate", @"9",
                            @"Professional", @"10",
                            nil];
    
    NSDictionary *education = [NSDictionary dictionaryWithObjectsAndKeys:
                               @"No Requirement", @"1",
                               @"High School", @"2",
                               @"Advanced Degree", @"5",
                               @"Bachelor's Degree", @"7",
                               @"Associate Degree", @"6",
                               nil];
    
    NSDictionary *workauth = [NSDictionary dictionaryWithObjectsAndKeys:
                              @"No Requirement", @"1",
                              @"W2", @"2",
                              @"Green Card", @"4",
                              @"Citzen", @"3",
                              nil];
    
    NSDictionary *industry = [NSDictionary dictionaryWithObjectsAndKeys:
                              @"Accounting and Auditing Services",@"14",
                              @"Advertising and PR Services",@"15",
                              @"Aerospace and Defense",@"16",
                              @"Agriculture/Forestry/Fishing",@"17",
                              @"Architectural and Design Services",@"18",
                              @"Automotive and Parts Mfg",@"19",
                              @"Automotive Sales and Repair Services",@"20",
                              @"Banking",@"21",
                              @"Biotechnology/Pharmaceuticals",@"22",
                              @"Broadcasting, Music, and Film",@"23",
                              @"Business Services - Other",@"24",
                              @"Chemicals/Petro-Chemicals",@"25",
                              @"Clothing and Textile Manufacturing",@"26",
                              @"Computer Hardware",@"27",
                              @"Computer Software",@"28",
                              @"Computer/IT Services",@"29",
                              @"Construction - Industrial Facilities and Infrastructure",@"30",
                              @"Construction - Residential & Commercial/Office",@"31",
                              @"Consumer Packaged Goods Manufacturing",@"32",
                              @"Education",@"33",
                              @"Electronics, Components, and Semiconductor Mfg",@"34",
                              @"Energy and Utilities",@"35",
                              @"Engineering Services",@"36",
                              @"Entertainment Venues and Theaters",@"37",
                              @"Financial Services",@"38",
                              @"Food and Beverage Production",@"39",
                              @"Government and Military",@"40",
                              @"Healthcare Services",@"41",
                              @"Hotels and Lodging",@"42",
                              @"Insurance",@"43",
                              @"Internet Services",@"44",
                              @"Legal Services",@"45",
                              @"Management Consulting Services",@"46",
                              @"Manufacturing - Other",@"47",
                              @"Marine Mfg & Services",@"48",
                              @"Medical Devices and Supplies",@"49",
                              @"Metals and Minerals",@"50",
                              @"Nonprofit Charitable Organizations",@"51",
                              @"Other/Not Classified",@"52",
                              @"Performing and Fine Arts",@"53",
                              @"Personal and Household Services",@"54",
                              @"Printing and Publishing ",@"55",
                              @"Real Estate/Property Management",@"56",
                              @"Rental Services",@"57",
                              @"Restaurant/Food Services",@"58",
                              @"Retail",@"59",
                              @"Security and Surveillance",@"60",
                              @"Sports and Physical Recreation",@"61",
                              @"Staffing/Employment Agencies",@"62",
                              @"Telecommunications Services",@"63",
                              @"Transport and Storage - Materials ",@"64",
                              @"Travel, Transportation and Tourism",@"65",
                              @"Waste Management",@"66",
                              @"Wholesale Trade/Import-Export",@"67",
                              nil];
        
    NSDictionary *yearsOfExp = [NSDictionary dictionaryWithObjectsAndKeys:
                                @"No Requirement",@"0",
                                @"1 Year",@"1",
                                @"2 Year",@"2",
                                @"3 Year",@"3",
                                @"4 Year",@"4",
                                @"5 Year",@"5",
                                @"6 Year",@"6",
                                @"7 Year",@"7",
                                @"8 Year",@"8",
                                @"9 Year",@"9",
                                @"10 Year",@"10",
                                @"10+ Year",@"11",
                                @"15+ Year",@"12",
                                nil];
    
    NSDictionary *salaryRange = @{
                                 @"0":@"No Requirement",
                                 @"1":@"Negotiable",
                                 @"2":@"~$30,000",
                                 @"3":@"~$50,000",
                                 @"4":@"~$70,000",
                                 @"5":@"~$90,000",
                                 @"6":@"~$100,000",
                                 @"7":@"$150,000",
                                 @"8":@"$150,000 +"
                                 };
    
    NSDictionary *careerLevel = @{
                                 @"0":@"No Requirements",
                                 @"12":@"Student (High School)",
                                 @"13":@"Student (Undergraduate/Graduate)",
                                 @"7":@"Entry Level",
                                 @"9":@"Experienced (Non-Manager)",
                                 @"10":@"Manager (Manager/Supervisor of Staff)",
                                 @"8":@"Executive (SVP, VP, Department Head, etc)",
                                 @"11":@"Senior Executive (President, CFO, etc)",
                                 };
    
    NSDictionary *skillLevel = @{
                                 @"0": @"No Experience",
                                 @"1": @"Expert",
                                 @"2": @"Experienced",
                                 @"3": @"Know Of",
                                 @"4": @"Novice"
                                 };
    
    NSDictionary *skills = @{
                             @"Java": @"Java",
                             @"Oracle": @"Oracle",
                             @"Amazon Cloud": @"Amazon Cloud",
                             @"Database": @"Database",
                             @"Search": @"Search",
                             @"Hadoop": @"Hadoop",
                             @"Communication": @"Communication",
                             @"Html": @"Html"
                             };
    
    NSDictionary *transferableSkills = @{
                             @"Communication": @[
                                     @"writes clearly and concisely",
                                     @"speaks effectively",
                                     @"listens attentively",
                                     @"openly expresses ideas",
                                     @"negotiates/resolves differences",
                                     @"leads group discussions",
                                     @"provides feedback",
                                     @"persuades others",
                                     @"provides well-thought out solutions",
                                     @"gathers appropriate information",
                                     @"confidently speaks in public"
                                     ],
                             @"Interpersonal Skills": @[
                                     @"works well with others sensitive",
                                     @"supportive",
                                     @" motivates others",
                                     @"shares credit",
                                     @"counsels",
                                     @"cooperates",
                                     @"delegates effectively",
                                     @"represents others",
                                     @"understands feelings",
                                     @"self-confident",
                                     @"accepts responsibility"

                                     ],
                             @"Research and Planning": @[
                                     @"forecasts/predicts",
                                     @"creates ideas",
                                     @"identifies problems",
                                     @"meets goals",
                                     @"identifies resources",
                                     @"gathers information",
                                     @"solves problems",
                                     @"defines needs",
                                     @"analyzes issues",
                                     @"develops strategies",
                                     @"assesses situations"
                                     ],
                             @"Organizational Skills": @[
                                     @"handles details",
                                     @"coordinates tasks",
                                     @"punctual",
                                     @"manages projects effectively",
                                     @"meets deadlines",
                                     @"sets goals",
                                     @"keeps control over budget",
                                     @"plans and arranges activities",
                                     @"multi-tasks"

                                     ],
                             @"Management Skills": @[
                                     @"leads groups",
                                     @"teaches/trains/instructs",
                                     @"counsels/coaches",
                                     @"manages conflict",
                                     @"delegates responsibility",
                                     @"makes decisions",
                                     @"directs others",
                                     @"implements decisions",
                                     @"enforces policies",
                                     @"takes charge"
                                     ]
                             };
    
    [lovs setObject:userTypes forKey:@"userType"];
    [lovs setObject:jobTitles forKey:JOB_TITLE];
    [lovs setObject:careerLevel forKey:CAREER_LEVEL];
   // [lovs setObject:group forKey:GROUPS];
    [lovs setObject:metroAreas forKey:METRO_AREA];
    [lovs setObject:education forKey:EDUCATION_LEVEL];
    [lovs setObject:industry forKey:INDUSTRY];
    [lovs setObject:degree forKey:DEGREE];
    [lovs setObject:terms forKey:EMPLOYMENT_TYPE];
    [lovs setObject:salaryRange forKey:PAY_RATE];
    [lovs setObject:yearsOfExp forKey:EXPERIENCE_YEARS];
    [lovs setObject:skillLevel forKey:SKILL_LEVEL];
    [lovs setObject:skills forKey:SKILL];
    [lovs setObject:workauth forKey:WORK_AUTH];
    [lovs setObject:transferableSkills forKey:SOFT_SKILL];
    NSDictionary *restrictions = [NSDictionary dictionaryWithObjectsAndKeys: nil];
    [lovs setObject:restrictions forKey:INVITATION_RESTRICTIONS];
    return lovs;
}



@end
