package org.sixstreams.social;

import java.util.HashMap;
import java.util.Map;

import org.sixstreams.search.data.java.ListOfValues;

public class LocationCountryLov extends ListOfValues{
	
	private Map<String, Object> lov = new HashMap<String, Object>();
	
	public Map<String, Object> getLov()
	{
		return lov;
	}
	
	public LocationCountryLov()
	{
		lov.put("atlanta-ga", "Atlanta, GA");
		lov.put("us", "United States");
		lov.put("ca", "Canada");
		lov.put("af", "Afghanistan");
		lov.put("al", "Albania");
		lov.put("dz", "Algeria");
		lov.put("as", "American Samoa");
		lov.put("ad", "Andorra");
		lov.put("ao", "Angola");
		lov.put("ai", "Anguilla");
		lov.put("aq", "Antarctica");
		lov.put("ag", "Antigua and Barbuda");
		lov.put("ar", "Argentina");
		lov.put("am", "Armenia");
		lov.put("aw", "Aruba");
		lov.put("au", "Australia");
		lov.put("at", "Austria");
		lov.put("az", "Azerbaijan");
		lov.put("bs", "Bahamas");
		lov.put("bh", "Bahrain");
		lov.put("bd", "Bangladesh");
		lov.put("bb", "Barbados");
		lov.put("by", "Belarus");
		lov.put("be", "Belgium");
		lov.put("bz", "Belize");
		lov.put("bj", "Benin");
		lov.put("bm", "Bermuda");
		lov.put("bt", "Bhutan");
		lov.put("bo", "Bolivia");
		lov.put("ba", "Bosnia and Herzegovina");
		lov.put("bw", "Botswana");
		lov.put("bv", "Bouvet Island");
		lov.put("br", "Brazil");
		lov.put("io", "British Indian Ocean Territory");
		lov.put("bn", "Brunei Darussalam");
		lov.put("bg", "Bulgaria");
		lov.put("bf", "Burkina Faso");
		lov.put("bi", "Burundi");
		lov.put("kh", "Cambodia");
		lov.put("cm", "Cameroon");
		lov.put("cv", "Cape Verde");
		lov.put("ky", "Cayman Islands");
		lov.put("cf", "Central African Republic");
		lov.put("td", "Chad");
		lov.put("cl", "Chile");
		lov.put("cn", "China");
		lov.put("cx", "Christmas Island");
		lov.put("cc", "Cocos (Keeling) Islands");
		lov.put("co", "Colombia");
		lov.put("km", "Comoros");
		lov.put("cg", "Congo");
		lov.put("cd", "Congo, The Democratic Republic of the");
		lov.put("ck", "Cook Islands");
		lov.put("cr", "Costa Rica");
		lov.put("ci", "Cote D'Ivoire");
		lov.put("hr", "Croatia");
		lov.put("cu", "Cuba- Guantanamo Bay");
		lov.put("cy", "Cyprus");
		lov.put("cz", "Czech Republic");
		lov.put("dk", "Denmark");
		lov.put("dj", "Djibouti");
		lov.put("dm", "Dominica");
		lov.put("do", "Dominican Republic");
		lov.put("tl", "East Timor");
		lov.put("ec", "Ecuador");
		lov.put("eg", "Egypt");
		lov.put("sv", "El Salvador");
		lov.put("gq", "Equatorial Guinea");
		lov.put("er", "Eritrea");
		lov.put("ee", "Estonia");
		lov.put("et", "Ethiopia");
		lov.put("fk", "Falkland Islands(Malvinas)");
		lov.put("fo", "Faroe Islands");
		lov.put("fj", "Fiji");
		lov.put("fi", "Finland");
		lov.put("fr", "France");
		lov.put("gf", "French Guiana");
		lov.put("pf", "French Polynesia");
		lov.put("tf", "French Southern Territories");
		lov.put("ga", "Gabon");
		lov.put("gm", "Gambia");
		lov.put("ps", "Gaza Strip, West Bank");
		lov.put("ge", "Georgia");
		lov.put("de", "Germany");
		lov.put("gh", "Ghana");
		lov.put("gi", "Gibraltar");
		lov.put("gr", "Greece");
		lov.put("gl", "Greenland");
		lov.put("gd", "Grenada");
		lov.put("gp", "Guadeloupe");
		lov.put("gu", "Guam");
		lov.put("gt", "Guatemala");
		lov.put("gn", "Guinea");
		lov.put("gw", "Guinea-Bissau");
		lov.put("gy", "Guyana");
		lov.put("ht", "Haiti");
		lov.put("hm", "Heard and McDonald Islands");
		lov.put("va", "Holy See (Vatican City State)");
		lov.put("hn", "Honduras");
		lov.put("hk", "Hong Kong");
		lov.put("hu", "Hungary");
		lov.put("is", "Iceland");
		lov.put("in", "India");
		lov.put("id", "Indonesia");
		lov.put("iq", "Iraq");
		lov.put("ie", "Ireland");
		lov.put("il", "Israel");
		lov.put("it", "Italy");
		lov.put("jm", "Jamaica");
		lov.put("jp", "Japan");
		lov.put("jo", "Jordan");
		lov.put("kz", "Kazakhstan");
		lov.put("ke", "Kenya");
		lov.put("ki", "Kiribati");
		lov.put("kp", "Korea, Democratic People's Rep of");
		lov.put("kr", "Korea, Republic of");
		lov.put("kw", "Kuwait");
		lov.put("kg", "Kyrgyzstan");
		lov.put("la", "Lao People's Democratic Republic");
		lov.put("lv", "Latvia");
		lov.put("lb", "Lebanon");
		lov.put("ls", "Lesotho");
		lov.put("lr", "Liberia");
		lov.put("ly", "Libyan Arab Jamahiriya");
		lov.put("li", "Liechtenstein");
		lov.put("lt", "Lithuania");
		lov.put("lu", "Luxembourg");
		lov.put("mo", "Macao");
		lov.put("mk", "Macedonia, The Frmr Yugoslav Rep of");
		lov.put("mg", "Madagascar");
		lov.put("mw", "Malawi");
		lov.put("my", "Malaysia");
		lov.put("mv", "Maldives");
		lov.put("ml", "Mali");
		lov.put("mt", "Malta");
		lov.put("mh", "Marshall Islands");
		lov.put("mq", "Martinique");
		lov.put("mr", "Mauritania");
		lov.put("mu", "Mauritius");
		lov.put("yt", "Mayotte");
		lov.put("mx", "Mexico");
		lov.put("fm", "Micronesia, Federated States of");
		lov.put("md", "Moldova, Republic of");
		lov.put("mc", "Monaco");
		lov.put("mn", "Mongolia");
		lov.put("ms", "Montserrat");
		lov.put("ma", "Morocco");
		lov.put("mz", "Mozambique");
		lov.put("mm", "Myanmar");
		lov.put("na", "Namibia");
		lov.put("nr", "Nauru");
		lov.put("np", "Nepal");
		lov.put("nl", "Netherlands");
		lov.put("an", "Netherlands Antilles");
		lov.put("nc", "New Caledonia");
		lov.put("nz", "New Zealand");
		lov.put("ni", "Nicaragua");
		lov.put("ne", "Niger");
		lov.put("ng", "Nigeria");
		lov.put("nu", "Niue");
		lov.put("nf", "Norfolk Island");
		lov.put("mp", "Northern Mariana Islands");
		lov.put("no", "Norway");
		lov.put("om", "Oman");
		lov.put("pk", "Pakistan");
		lov.put("pw", "Palau");
		lov.put("pa", "Panama");
		lov.put("pg", "Papua New Guinea");
		lov.put("py", "Paraguay");
		lov.put("pe", "Peru");
		lov.put("ph", "Philippines");
		lov.put("pn", "Pitcairn");
		lov.put("pl", "Poland");
		lov.put("pt", "Portugal");
		lov.put("pr", "Puerto Rico");
		lov.put("qa", "Qatar");
		lov.put("re", "Reunion");
		lov.put("ro", "Romania");
		lov.put("ru", "Russian Federation");
		lov.put("rw", "Rwanda");
		lov.put("gs", "S. Georgia and S. Sandwich Isles.");
		lov.put("sh", "Saint Helena");
		lov.put("kn", "Saint Kitts and Nevis Anguilla");
		lov.put("lc", "Saint Lucia");
		lov.put("pm", "Saint Pierre and Miquelon");
		lov.put("vc", "Saint Vincent and Grenadines");
		lov.put("ws", "Samoa");
		lov.put("sm", "San Marino");
		lov.put("st", "Sao Tome and Principe");
		lov.put("sa", "Saudi Arabia");
		lov.put("sn", "Senegal");
		lov.put("sc", "Seychelles");
		lov.put("sl", "Sierra Leone");
		lov.put("sg", "Singapore");
		lov.put("sk", "Slovakia");
		lov.put("si", "Slovenia");
		lov.put("sb", "Solomon Islands");
		lov.put("so", "Somalia");
		lov.put("za", "South Africa");
		lov.put("es", "Spain");
		lov.put("lk", "Sri Lanka");
		lov.put("sr", "Suriname");
		lov.put("sj", "Svalbard and Jan Mayen");
		lov.put("sz", "Swaziland");
		lov.put("se", "Sweden");
		lov.put("ch", "Switzerland");
		lov.put("tw", "Taiwan, Province of China");
		lov.put("tj", "Tajikistan");
		lov.put("tz", "Tanzania, United Republic of");
		lov.put("th", "Thailand");
		lov.put("tg", "Togo");
		lov.put("tk", "Tokelau");
		lov.put("to", "Tonga");
		lov.put("tt", "Trinidad and Tobago");
		lov.put("tn", "Tunisia");
		lov.put("tr", "Turkey");
		lov.put("tm", "Turkmenistan");
		lov.put("tc", "Turks and Caicos Islands");
		lov.put("tv", "Tuvalu");
		lov.put("ug", "Uganda");
		lov.put("ua", "Ukraine");
		lov.put("ae", "United Arab Emirates");
		lov.put("gb", "United Kingdom");
		lov.put("um", "United States Minor Outlying Isl");
		lov.put("uy", "Uruguay");
		lov.put("uz", "Uzbekistan");
		lov.put("vu", "Vanuatu");
		lov.put("ve", "Venezuela");
		lov.put("vn", "Viet Nam");
		lov.put("vg", "Virgin Islands, British");
		lov.put("vi", "Virgin Islands, U.S.");
		lov.put("wf", "Wallis and Futuna Islands");
		lov.put("eh", "Western Sahara");
		lov.put("yu", "Yemen");
		lov.put("yu", "Yugoslavia");
		lov.put("zm", "Zambia");
		lov.put("zw", "Zimbabwe");
	}
}
